apiVersion:v1
kind:Service
metadata:
  name: demoapp-service
spec:
  selector:
    app: demoapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30088
  type: NodePort